Fix profiler for shardings.py
google/maxtext pull request #165
Opened 2023-09-19 19:40 UTC by khatwanimohit

Tested on stable `JAX==0.4.16` and nightly `0.4.17.dev20230919`

2023-09-19 20:49 UTC, yashs97 approved these changes

2023-09-20 15:01 UTC, rwitten requested changes
I need some context! Why is this change needed? What problem does it solve?

In the past we put it where we put it because we didn't want to profile the compile.

2023-09-20 19:44 UTC, khatwanimohit commented
> What problem does it solve?
Currently profiling throws a segmentation fault if start_trace is called within `with` statement

2023-09-22 19:59 UTC, rwitten approved these changes
THanks!

2023-09-22 21:10 UTC, merged