Add a flag in multihost_job.py to enable Autocheckpoint
google/maxtext pull request #197
Opened 2023-10-04 17:33 UTC by xuefgu

This change allows the users to launch a production-ready MaxText job with the Autocheckpoint feature enabled on Cloud TPU.

It is tested by first launching a job with:
```
NODE_COUNT=2
python3 multihost_job.py --NUM_SLICES=$NODE_COUNT --RUN_NAME=$RUN_NAME --TPU_TYPE=v4-8 --VERSION=tpu-ubuntu2204-base --BUCKET_NAME=$BUCKET_NAME --ENABLE_AUTOCHECKPOINT=true \
--COMMAND="bash setup.sh && python3 MaxText/train.py MaxText/configs/base.yml run_name=$RUN_NAME global_parameter_scale=2 per_device_batch_size=6 save_period=50 base_output_directory=$OUTPUT_DIR dataset_path=$DATASET_PATH"
```
and then observing that the checkpoint does get saved upon a disruption.

2023-10-04 20:09 UTC, rwitten requested changes
Do we need this. Isn't this covered by --CQR_EXTRA_ARGS?

2023-10-04 20:39 UTC, xuefgu commented
> Do we need this. Isn't this covered by --CQR_EXTRA_ARGS?

We could have the user pass the `--autocheckpoint-enabled` flag in `--CQR_EXTRA_ARGS`. This PR is to make MaxText support the feature from the top-level, without the user having to look into how to enable the feature in the CQR request. I can see the pros/cons both ways.

2023-10-06 16:32 UTC, rwitten reviewed
If we want to merge this, let's do it when ENABLE_AUTOCHECKPOINT is ready to be true by default.

2023-10-17 03:28 UTC, rwitten approved these changes

2023-10-17 15:56 UTC, merged