Tensorboard instructions frequency
google/maxtext pull request #26
Opened 2023-05-03 17:02 UTC by priyanka-ganesha

Print tensorboard instructions every 5 steps and if profiler is enabled

2023-05-03 19:26 UTC, rwitten requested changes

2023-05-03 19:26 UTC, rwitten commented on MaxText/train.py
> +          f"PROFILING: To see full metrics 'tensorboard --logdir={config.tensorboard_dir}'"
Tensorboard produces data even with profiling off! It shouldn't be tied to the profiler.

2023-05-03 19:26 UTC, rwitten commented on MaxText/train.py
> +    full_log = step % 5 == 0
I don't love adding more constants scatter around the codebase and not sure I fully understand this particular one. Does the `log_period` only influence this or are there other consumers? If there aren't any other consumers, maybe we just set the default `log_period` to say 10?

2023-05-11 17:18 UTC, gobbleturk approved these changes
As we're only changing the frequency of the tensorboard command print, this is fine

2023-05-11 17:21 UTC, rwitten approved these changes

2023-05-11 17:22 UTC, merged