Add kubectl and gke-gcloud-auth-plugin to maxtext dependency dockerfile
google/maxtext pull request #357
Opened 2024-01-18 21:21 UTC by raymondzouu

This change is needed to be able to run MaxText/XPK-based XLML tests on the new Airflow-based infra. The infra executes the XPK command using KubernetesPodOperator on the docker image https://github.com/GoogleCloudPlatform/ml-auto-solutions/blob/a0287d3730ccd9d2b24ac2339dbb1cd42386f9e7/xlml/utils/xpk.py#L50-L57. KubernetesPodOperator needs `kubectl` and `google-cloud-sdk-gke-gcloud-auth-plugin`.

2024-01-18 21:50 UTC, tonyjohnchen approved these changes

2024-01-18 23:15 UTC, rwitten commented
This docker image is building a runner -- a.k.a. an env where MaxText runs. Why does that env need to know about Kubectl etc?

2024-01-18 23:16 UTC, rwitten requested changes
I don't understand this change! Doesn't seem like a MaxText runner (i.e. a GPU/TPU ndoe) should need to know about kubectl.

2024-01-23 17:53 UTC, raymondzouu commented
The MaxText runner docker image needed kubectl since XLML currently uses the runner docker image to execute the XPK command with KubernetePodsOperator. Instead of it installing it here for all use cases, I made a change in the XLML codebase such that the XLML test will install it in the image only when needed. I will close out this PR as it is no longer needed.

2024-01-23 17:53 UTC, closed without merging