Adds microbenchmarking and uses standard 1e9 for memory calcs.
google/maxtext pull request #509
Opened 2024-03-13 00:33 UTC by patemotter

Will need to add a smoke test appended to this pr or in the next pr when adding/changing the benchmark.

2024-03-13 18:57 UTC, rwitten requested changes
Some nits!

P.S. - for faster responses in the future, please mark me as having next steps!

2024-03-13 18:57 UTC, rwitten commented on MaxText/decode.py
> +from jax.experimental.compilation_cache import compilation_cache as cc
Can you put this into pyconfig as we discussed?

2024-03-13 18:57 UTC, rwitten commented on MaxText/microbenchmark.py
> +"""Tests for a mock version of the engine API, used in integration tests elsewhere.
inference_microbenchmark? I think?

2024-03-13 18:57 UTC, rwitten commented on MaxText/microbenchmark.py
> +"""Tests for a mock version of the engine API, used in integration tests elsewhere.
Also this prefix will cause problems (and is wrong).

2024-03-13 18:57 UTC, rwitten commented on MaxText/microbenchmark.py
> +  with open("benchmark_results.json", "w") as f:
can you make sure that sharegpt analysis can consume this? (And you can remove idealization from the sharegpt analysis.)

2024-03-13 18:57 UTC, rwitten commented on MaxText/microbenchmark.py
> +  os.environ["M_ICI_AUTOREGRESSIVE_PARALLELISM"] = "-1"
pretty intense. I'd like you to hold off on this. In the future we might want different settings.

2024-03-13 18:57 UTC, rwitten commented on run_microbenchmark.sh
> +export M_ICI_AUTOREGRESSIVE_PARALLELISM=-1
can we put this into the inference scratch world?

2024-03-13 23:48 UTC, patemotter commented
1. Improved readability of benchmark output. 
2. Now prints two lines that you can either copy and paste into sharegpt_analyze.py or you can load the json output directly. 
3. Refactored the analyze_sharegpt.py script. 
4. Moved cache compilation method out of individual scripts and into pyconfig.

2024-03-14 00:18 UTC, patemotter commented
Removed unnecessary engine inits.

2024-03-15 18:02 UTC, closed without merging